version: "3.3"
networks:
    media-collection:
services:
    transmission:
        container_name: transmission
        cap_add:
            - NET_ADMIN
        volumes:
            - "/media/data/transmission/data:/data"
            - "/root/transmission/config:/config"
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=turkey
            - LOCAL_NETWORK=192.168.0.0/16
            - OPENVPN_USERNAME=$OPENVPN_USERNAME
            - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
            - TRANSMISSION_WEB_UI=flood-for-transmission
            - CREATE_TUN_DEVICE=true
            - TZ=Europe/Oslo
        logging:
            driver: json-file
            options:
                max-size: 10m
        image: haugene/transmission-openvpn:dev
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.transmission.rule=Host(`transmission.arceus.box`)"
            - "traefik.http.routers.transmission.entrypoints=web"
            - "traefik.http.services.transmission.loadbalancer.server.port=9091"
        networks:
            - media-collection
    jackett:
        container_name: jackett
        volumes:
            - "/root/jackett/configs/jackett:/config"
            - "/media/data/jackett/downloads/jackett:/downloads"
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Oslo
        image: lscr.io/linuxserver/jackett:latest
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jackett.rule=Host(`jackett.arceus.box`)"
            - "traefik.http.routers.jackett.entrypoints=web"
            - "traefik.http.services.jackett.loadbalancer.server.port=9117"
        networks:
            - media-collection
    sonarr:
        container_name: sonarr
        volumes:
            - "/root/sonarr/configs/sonarr:/config"
            - "/media/data/plex/tv:/tv"
            - "/media/data/transmission/data/completed:/data/completed"
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Oslo
        image: lscr.io/linuxserver/sonarr:latest
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr.rule=Host(`sonarr.arceus.box`)"
            - "traefik.http.routers.sonarr.entrypoints=web"
            - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        networks:
            - media-collection
    radarr:
        container_name: radarr
        volumes:
            - "/root/radarr/configs/radarr:/config"
            - "/media/data/plex/movies:/movies"
            - "/media/data/transmission/data/completed:/data/completed"
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Oslo
        image: lscr.io/linuxserver/radarr:latest
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.radarr.rule=Host(`radarr.arceus.box`)"
            - "traefik.http.routers.radarr.entrypoints=web"
            - "traefik.http.services.radarr.loadbalancer.server.port=7878"
        networks:
            - media-collection
    bazarr:
        container_name: bazarr
        image: lscr.io/linuxserver/bazarr:latest
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/London
        volumes:
            - "/root/bazarr/configs/bazarr:/config"
            - "/media/data/plex/movies:/movies"
            - "/media/data/plex/tv:/tv"
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bazarr.rule=Host(`bazarr.arceus.box`)"
            - "traefik.http.routers.bazarr.entrypoints=web"
            - "traefik.http.services.bazarr.loadbalancer.server.port=6767"