---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - /root/plex/config:/config
      - /media/data/plex/tv:/tv
      - /media/data/plex/movies:/movies
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.arceus.box`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.services.plex-plex.loadbalancer.server.port=32400"
