services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
    - /media/data/kuma:/app/data
    - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.kuma.rule=Host(`kuma.arceus.box`)"
    - "traefik.http.services.kuma.loadbalancer.server.port=3001"
    - "traefik.http.routers.kuma.entrypoints=web"